### ISSUE TITLE
[Bug]: Wrong certificate uploaded to tenant during "Generate certificates" command

### ISSUE THREAD

**Issue by vduseev** [dynatrace-extensions/dynatrace-extensions-vscode#225]
## Summary

It seems that for `Generate certificates` command or `Initialize workspace` command (which includes certificates generation as a step, so same logic, essentially) the wrong certificate is uploaded to the tenant. 

When you then build an extension and sign it with that certificate, the following error is returned by the tenant:

Dynatrace Log output:

```
2024-07-01T14:38:21.293Z [INFO][dynatrace-extensions.buildExtension] Command called.
2024-07-01T14:38:21.293Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T14:38:21.306Z [INFO][utils.conditionCheckers.isExtensionsWorkspace] Is this an extensions workspace? true
2024-07-01T14:38:21.323Z [INFO][utils.conditionCheckers.checkCertificateExists] Does DEV certificates exist? true
2024-07-01T14:38:21.331Z [INFO][utils.conditionCheckers.checkNoProblemsInManifest] Are there problems in the manifest? true
2024-07-01T14:38:21.335Z [INFO][commandPalette.buildExtension.buildExtension] Executing Build Extension command
2024-07-01T14:38:21.822Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T14:38:21.872Z [INFO][commandPalette.buildExtension.assembleStandard] Built the inner archive: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip
2024-07-01T14:38:21.882Z [INFO][utils.cryptography.sign] Signing extension with credentials from /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem
2024-07-01T14:38:22.004Z [INFO][commandPalette.buildExtension.assembleStandard] Wrote the signature file: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip.sig
2024-07-01T14:38:22.016Z [INFO][commandPalette.buildExtension.assembleStandard] Wrote initial outer zip at: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/custom_my.awesome.test-0.0.1.zip
2024-07-01T14:38:22.547Z [INFO][dynatrace-extensions.buildExtension] Completed normally
2024-07-01T14:38:22.557Z [ERROR][] Extension validation failed.
```

Dynatrace output:

```json
{
  "code": 400,
  "message": "Extension signature is not valid"
}
```

### Steps to reproduce

# Initial configuration

1. Clean or existing installation of VS Code add-on (both tested)
2. Set it up to be connected to the dev tenant
3. Create a new folder
4. Open this empty folder with VS Code
5. Invoke `Initialize workspace` or click the button with the same text in "Dynatrace extensions" sidebar
6. Go through the steps, choose to `Generate new ones` when selecting which certificates to use
7. Choose "Yes" to set these certificates as default for all workspaces
8. Choose "Yes" to upload the CA certificate to Dynatrace
9. You receive an error: `Cannot initialize workspace without certificates.`

Here, I'm overwriting the existing certificate but I've verified that the behavior is the same when the certificate doesn't exist.

```
2024-07-01T19:32:10.495Z [INFO][dynatrace-extensions.initWorkspace] Command called.
2024-07-01T19:32:10.496Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T19:32:10.510Z [INFO][utils.conditionCheckers.checkEnvironmentConnected] Is a tenant connected? true
2024-07-01T19:32:10.522Z [INFO][commandPalette.initWorkspace.initWorkspace] Executing Initialize Workspace command
2024-07-01T19:32:10.534Z [INFO][commandPalette.initWorkspace.initWorkspace] Using cached schema version 1.291.0
2024-07-01T19:32:10.886Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:32:10.911Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:32:32.711Z [INFO][dynatrace-extensions.generateCertificates] Command called.
2024-07-01T19:32:32.726Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T19:32:32.734Z [INFO][utils.conditionCheckers.checkOverwriteCertificates] Can continue and overwrite certificates? true
2024-07-01T19:32:32.743Z [INFO][commandPalette.generateCertificates.generateCerts] Executing Generate Certificates command
2024-07-01T19:32:33.254Z [INFO][commandPalette.generateCertificates.generateCerts] Generating CA certificate
2024-07-01T19:32:33.348Z [INFO][commandPalette.generateCertificates.generateCerts] CA Cert created successfully
2024-07-01T19:32:33.360Z [INFO][commandPalette.generateCertificates.generateCerts] Generating RSA key pair for Developer certificate
2024-07-01T19:32:33.488Z [INFO][commandPalette.generateCertificates.generateCerts] Generating the Developer certificate
2024-07-01T19:32:33.576Z [INFO][commandPalette.generateCertificates.generateCerts] DEV Cert created successfully
2024-07-01T19:32:33.590Z [INFO][commandPalette.generateCertificates.generateCerts] Writing certificates to disk
2024-07-01T19:32:33.603Z [INFO][commandPalette.generateCertificates.generateCerts] Wrote all certificates at location /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates
2024-07-01T19:32:33.617Z [INFO][commandPalette.generateCertificates.generateCerts] Updating vscode settings
2024-07-01T19:33:21.526Z [INFO][dynatrace-extensions.distributeCertificate] Command called.
2024-07-01T19:33:21.537Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T19:33:21.546Z [INFO][utils.conditionCheckers.checkEnvironmentConnected] Is a tenant connected? true
2024-07-01T19:33:21.557Z [INFO][utils.conditionCheckers.checkCertificateExists] Does CA certificates exist? true
2024-07-01T19:33:21.566Z [INFO][commandPalette.distributeCertificate] Executing Distribute Certificate command
2024-07-01T19:33:21.949Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:33:21.960Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:33:30.356Z [INFO][utils.conditionCheckers.checkActiveGateInstalled] Is ActiveGate installed locally? false
2024-07-01T19:33:30.357Z [INFO][utils.conditionCheckers.checkOneAgentInstalled] Is OneAgent installed locally? > false
2024-07-01T19:33:30.369Z [INFO][dynatrace-extensions.distributeCertificate] Completed normally
2024-07-01T19:33:30.376Z [INFO][dynatrace-extensions.generateCertificates] Completed normally
2024-07-01T19:33:30.383Z [ERROR][commandPalette.initWorkspace.initWorkspace] Workspace initialization aborted due to earlier failure.
2024-07-01T19:33:30.400Z [INFO][dynatrace-extensions.initWorkspace] Completed normally
2024-07-01T19:34:03.064Z [ERROR][commandPalette.initWorkspace.initWorkspace] Cannot initialize workspace without certificates.
2024-07-01T19:34:04.357Z [INFO][commandPalette.distributeCertificate] Certificate successfully updated in the Credential Vault.
```

# Initialize workspace the second time

However, this error doesn't mean something is wrong. The certificates were successfully generated and the `ca.pem` file is uploaded to the tenant.

1. Click `Initialize workspace` again
2. Choose `Use existing` certificates this time, since we've just generated them
3. Choose `Extension 2.0`

```
2024-07-01T19:41:24.680Z [INFO][dynatrace-extensions.initWorkspace] Command called.
2024-07-01T19:41:24.688Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T19:41:24.697Z [INFO][utils.conditionCheckers.checkEnvironmentConnected] Is a tenant connected? true
2024-07-01T19:41:24.708Z [INFO][commandPalette.initWorkspace.initWorkspace] Executing Initialize Workspace command
2024-07-01T19:41:24.728Z [INFO][commandPalette.initWorkspace.initWorkspace] Using cached schema version 1.291.0
2024-07-01T19:41:25.130Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:41:25.149Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:41:27.862Z [INFO][utils.conditionCheckers.checkSettings] Settings developerCertkeyLocation exist? true
2024-07-01T19:41:46.416Z [INFO][dynatrace-extensions.initWorkspace] Completed normally
```

Result: successful initialization of the extension

# Build the extension

1. Call `Dynatrace extensions: Build` command
2. The build process goes through up to the "Validation" phase

```json
{
  "code": 400,
  "message": "Extension signature is not valid"
}
```

```
2024-07-01T19:44:16.218Z [INFO][dynatrace-extensions.buildExtension] Command called.
2024-07-01T19:44:16.218Z [INFO][utils.conditionCheckers.checkWorkspaceOpen] Is a workspace open? true
2024-07-01T19:44:16.225Z [INFO][utils.conditionCheckers.isExtensionsWorkspace] Is this an extensions workspace? true
2024-07-01T19:44:16.230Z [INFO][utils.conditionCheckers.checkCertificateExists] Does DEV certificates exist? true
2024-07-01T19:44:16.236Z [INFO][utils.conditionCheckers.checkNoProblemsInManifest] Are there problems in the manifest? true
2024-07-01T19:44:16.243Z [INFO][commandPalette.buildExtension.buildExtension] Executing Build Extension command
2024-07-01T19:44:16.639Z [INFO][utils.conditionCheckers.checkUrlReachable] Is URL https://xxx.com/api/v1/time reachable? true
2024-07-01T19:44:16.702Z [INFO][commandPalette.buildExtension.assembleStandard] Built the inner archive: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip
2024-07-01T19:44:16.704Z [INFO][utils.cryptography.sign] Signing extension with credentials from /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem
2024-07-01T19:44:16.825Z [INFO][commandPalette.buildExtension.assembleStandard] Wrote the signature file: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip.sig
2024-07-01T19:44:16.831Z [INFO][commandPalette.buildExtension.assembleStandard] Wrote initial outer zip at: /Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/custom_my.awesome.extension-0.0.1.zip
2024-07-01T19:44:17.263Z [INFO][dynatrace-extensions.buildExtension] Completed normally
2024-07-01T19:44:17.271Z [ERROR][] Extension validation failed.
```

The built and signed extension produced by the VS Code add-on can still be found in the workspace storage:

```shell
$ ll "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/"                          
total 32
drwxr-xr-x  6 vagiz.duseev  staff   192B Jul  1 21:44 .
drwxr-xr-x  6 vagiz.duseev  staff   192B Jul  1 22:25 ..
-rw-r--r--@ 1 vagiz.duseev  staff   6.0K Jul  1 22:30 .DS_Store
drwxr-xr-x  9 vagiz.duseev  staff   288B Jul  1 21:32 certificates
-rw-rw-rw-  1 vagiz.duseev  staff   226B Jul  1 21:44 extension.zip
-rw-r--r--  1 vagiz.duseev  staff   2.8K Jul  1 21:44 extension.zip.sig
```

Let's manually put `extension.zip` and `extension.zip.sig` into a zip archive

```shell
$ zip bundle.zip extension.zip extension.zip.sig 
  adding: extension.zip (stored 0%)
  adding: extension.zip.sig (deflated 25%)
```

Uploading it to the tenant gives the same error: `Extension signature is not valid`.

# Let's check the certificates

First, triple checked that the certificate paths that end up in `settings.json` are the same as in the actual folder.

```json
{
    "dynatraceExtensions.developerCertkeyLocation": "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem",
    "dynatraceExtensions.rootOrCaCertificateLocation": "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/ca.pem",
}
```

Folder contents

```
$ ls -la 8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates 
total 64
drwxr-xr-x  9 vagiz.duseev  staff   288B Jul  1 21:32 .
drwxr-xr-x  6 vagiz.duseev  staff   192B Jul  1 21:44 ..
-rw-r--r--  1 vagiz.duseev  staff   3.2K Jul  1 21:32 ca.key
-rw-r--r--  1 vagiz.duseev  staff   1.8K Jul  1 21:32 ca.pem
-rw-r--r--  1 vagiz.duseev  staff   814B Jul  1 21:32 ca.pub.key
-rw-r--r--  1 vagiz.duseev  staff   3.2K Jul  1 21:32 dev.key
-rw-r--r--  1 vagiz.duseev  staff   1.9K Jul  1 21:32 dev.pem
-rw-r--r--  1 vagiz.duseev  staff   814B Jul  1 21:32 dev.pub.key
-rw-r--r--  1 vagiz.duseev  staff   5.1K Jul  1 21:32 developer.pem
```

## Try to build and sign the extension using dt-cli

Let's try to reproduce the process with `dt-cli` using the same generated certificates.

```shell
# Assemble the archive
$ dt ext assemble --src extension/ --output dist/extension.zip
Building dist/extension.zip from extension
Adding file: extension/extension.yaml as extension.yaml

# dt-cli refuses to sign an extension with `developer.pem` file from above because the file has a read permission for groups+all. Similarly to SSH keys, these certificates, ideally, would only be readable by the owner (`0400` permissions).
# Let's set correct permission for developer.pem file.
$ chmod 0400 "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem"

# Sign the bundle
$ dt ext sign --src dist/extension.zip --output dist/bundle.zip --key "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem"
```

Let's now upload that signed bundle to the tenant. 

1. If we do that manually, the tenant will report an error: `Extension signature is not valid`.
2. Same happens if we validate the signed bundle through `dt-cli` below (*the output is very ugly and scary and should be refactored to avoid stack trace printing*).

```shell
$ dt ext validate dist/bundle.zip --tenant-url https://xxx.com/ --api-token dt0c01.xxx
Extension validation failed!
Traceback (most recent call last):
  File "/Users/xxx/Projects/dt-cli/dtcli/server_api.py", line 32, in validate
    response.raise_for_status()
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xxx.com/api/v2/extensions?validateOnly=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dt", line 6, in <module>
    sys.exit(main())
  File "/Users/xxx/Projects/dt-cli/dtcli/__main__.py", line 5, in main
    dtcli.scripts.dt.main()
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/Projects/dt-cli/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xxx/Projects/dt-cli/dtcli/scripts/dt.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "/Users/xxx/Projects/dt-cli/dtcli/scripts/dt.py", line 747, in validate
    server_api.validate(extension_zip, kwargs["tenant_url"], kwargs["api_token"])
  File "/Users/xxx/Projects/dt-cli/dtcli/server_api.py", line 36, in validate
    raise dtcliutils.ExtensionValidationError(response.text)
dtcli.utils.ExtensionValidationError: {"error":{"code":400,"message":"Extension signature is not valid"}}
```

### Verify the signature using OpenSSL

Verification of the signature generated by VS Code add-on with the certificates generated by VS Code add-on above:

```shell
openssl cms -verify -CAfile "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/ca.pem" -in "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip.sig" -binary -content "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/extension.zip" -inform PEM -out /dev/null
CMS Verification failure
000C3D0302000000:error:17000064:CMS routines:cms_signerinfo_verify_cert:certificate verify error:crypto/cms/cms_smime.c:289:Verify error: certificate is not yet valid
```

Same procedure but for the bundle signed with `dt-cli` using the same certificates (generated by VS Code add-on):

```shell
$ openssl cms -verify -CAfile "/Users/xxx/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/ca.pem" -in dist/bundle/extension.zip.sig -binary -content dist/bun
dle/extension.zip -inform PEM -out /dev/null
CMS Verification failure
000C3D0302000000:error:17000064:CMS routines:cms_signerinfo_verify_cert:certificate verify error:crypto/cms/cms_smime.c:289:Verify error: certificate is not yet valid
```

The validity dates of the generated certificates are not exactly same, although I'm not sure how that affects the process. The output below is generated with `openssl x509 -noout -text -in "<path-to-cert.pem>"

`ca.pem`:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            4b:12:1c:16:69:f3:ab:04:87:ab:b5:be:08:ab:89:d0:f1:35:72:07
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Extension Developer Root
        Validity
            Not Before: Jun 30 19:32:33 2024 GMT
            Not After : Jul  1 19:32:33 2027 GMT
        Subject: CN=Extension Developer Root
```

`dev.pem`:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            72:43:b7:da:a6:e9:32:74:ca:76:c8:25:14:96:e5:d1:b9:a5:96:44
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Extension Developer Root
        Validity
            Not Before: Jul 29 19:32:33 2024 GMT
            Not After : Jul  1 19:32:33 2030 GMT
        Subject: CN=Extension Developer Dev
```

`developer.pem`:

```
openssl x509 -noout -text -in "/Users/vagiz.duseev/Library/Application Support/Code/User/workspaceStorage/8a857babd1976b2dedff29e86f7ac03e/DynatracePlatformExtensions.dynatrace-extensions/certificates/developer.pem"
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            72:43:b7:da:a6:e9:32:74:ca:76:c8:25:14:96:e5:d1:b9:a5:96:44
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Extension Developer Root
        Validity
            Not Before: Jul 29 19:32:33 2024 GMT
            Not After : Jul  1 19:32:33 2030 GMT
        Subject: CN=Extension Developer Dev
```

**Question**: why do we need an intermediate `dev.pem`?

## How to fix

Manually overwrite the deployed CA certificate with the `dev.pem` instead. 

### Support information

- [ ] Screenshots
- [ ] Extension manifest file
- [ ] YAML snippets
- [X] Support archive ([see here](https://developer.dynatrace.com/extensions-v2/dynatrace-extensions-vscode/troubleshooting/#collect-a-log-archive))

**Comment by radu-stefan-dt** [comment]
I can't reproduce this. Let's discuss offline.
